// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh34N2VO6miDY3ZfLRFYEF74WRctweFKw',
    appId: '1:556674691617:web:c9170d7b4cdc19a06ca960',
    messagingSenderId: '556674691617',
    projectId: 'development-env-412201',
    authDomain: 'development-env-412201.firebaseapp.com',
    databaseURL: 'https://development-env-412201-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'development-env-412201.appspot.com',
    measurementId: 'G-L764SHE7KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsjosM2e31rrjzu2Ujt3rKGuJ_xhavwfs',
    appId: '1:269459525970:android:6f7a738633c8dcfa77aa8b',
    messagingSenderId: '269459525970',
    projectId: 'vivid-grove-405713',
    databaseURL: 'https://vivid-grove-405713-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vivid-grove-405713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9i-0zQw301ddAQAcpi6Z7-EzoRqEeFus',
    appId: '1:269459525970:ios:b47ff1d2c353f4a377aa8b',
    messagingSenderId: '269459525970',
    projectId: 'vivid-grove-405713',
    databaseURL: 'https://vivid-grove-405713-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vivid-grove-405713.appspot.com',
    iosBundleId: 'com.perigigi.godentist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMQwKXzo4NLA_HM-_rRIohgweaI__ovxo',
    appId: '1:556674691617:ios:5eb05628025b4bd26ca960',
    messagingSenderId: '556674691617',
    projectId: 'development-env-412201',
    databaseURL: 'https://development-env-412201-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'development-env-412201.appspot.com',
    androidClientId: '556674691617-f9ihdd1ckjqkdvvjn99fq6jpncnf8djg.apps.googleusercontent.com',
    iosBundleId: 'com.example.goDentiest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh34N2VO6miDY3ZfLRFYEF74WRctweFKw',
    appId: '1:556674691617:web:478be9baf715292d6ca960',
    messagingSenderId: '556674691617',
    projectId: 'development-env-412201',
    authDomain: 'development-env-412201.firebaseapp.com',
    databaseURL: 'https://development-env-412201-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'development-env-412201.appspot.com',
    measurementId: 'G-02KGJLJ0GR',
  );
}